[build]
  publish = "."

[build.environment]
  NASA_API_KEY = "NASA_API_KEY_PLACEHOLDER"

[[plugins]]
  package = "netlify-plugin-replace"
  [plugins.inputs]
    files = ["app.js"]
    from = "NASA_API_KEY_PLACEHOLDER"
    to = "window.NASA_API_KEY" 